### ISSUE TITLE
megacli and LD lists

### ISSUE THREAD

**Issue by lrstanley** [sensu-plugins/sensu-plugins-raid-checks#13]
I am not a user of sensu nor do I directly utilize any plugins within this repo, however I have noticed what looks to be a bug with how you are checking the logical devices on Megaraid/LSI controllers.

Specifically, within https://github.com/sensu-plugins/sensu-plugins-raid-checks/blob/master/bin/check-megaraid-sas-status.rb -- it looks as though You first run the following:

```
$ /opt/MegaRAID/MegaCli/MegaCli64 -LDGetNum -a0
```

This returns a status code which equates to the number of logical devices there are. You then loop through the devices by index of zero, to the number of logical devices minus one: https://github.com/sensu-plugins/sensu-plugins-raid-checks/blob/master/bin/check-megaraid-sas-status.rb#L56. The problem with this is that megaraid cards do not always begin with index zero (e.g. spanning across multiple controllers, and/or if a LD is removed after a box has been kicked). Thus, the way that this loops through them is flawed.

For example, [here](http://dropb.in/t/gepfir) is a pastebin of some example output from a megaraid controller, showing output for `-LDGetNum` and `-LDInfo` for the array. As you can see, using index 0 won't always work.

I may suggest using `-LDInfo -LALL` and using regex to parse out `Virtual Drive: <number>` or a similar approach, which is a bit more flexible (as this type of output doesn't seem to change between versions).

Only a suggestion, though.

**Comment by majormoses** [comment]
@lrstanley thanks for reporting this, someone should definitely fix this, would you be willing to put together a pr? If not it I will probably not get around to it anytime soon since all my servers are in aws.

**Comment by lrstanley** [comment]
Sorry for the delay in getting back -- Unfortunately, I'm none too familiar with Ruby, so I don't think I'd be of much help making a pr.

I may be able to help test on a box with an LSI card, however.

**Comment by majormoses** [comment]
No worries, we are all busy right? I appreciate the report and willingness to help. Maybe someone who actually uses this or someone that works for sensu will take this up. I don't use this check and no active users atm are complaining so I have a hard time justifying spending  my "free time" to fix this over other issues were active users have reported. If you want to put together a gist in another language (anything but perl) I can work with you to translate into ruby and test.

**Comment by robertely** [comment]
Just ran into this myself actually @majormoses Are you working on this actively, would you like help ?

**Comment by majormoses** [comment]
@robertely sorry for the delayed response I am currently on vacation. I am not working on this but will review a PR if you want to submit one.
